[package]
name = "kroom-macros"
description = "Macro utils for kroom dependency injection library"
version = "0.1.0"
edition = "2024"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full","extra-traits"] }
quote = "1"
proc-macro2 = "1"
inventory = "0.3.24"

